[package]
name = "task_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.28.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "4.0"  # Para el manejo de argumentos en línea de comandos

